vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       videos: 
            uri_prefix: /images/videos
            upload_destination: '%kernel.project_dir%/public/images/video'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
